### ISSUE TITLE
Conflicts with WordFence 2FA login page

### ISSUE THREAD

**Issue by zackkatz** [trustedlogin/Remove-Dashboard-Access#33]
> Is there a way to exclude a specific URL from being blocked by this plugin? Specifically, we use Wordfence and have its two-factor authentication options enabled. However, users are being redirected away from the Wordfence two-factor configuration page when they click the activate button within their profile page.
> https://wordpress.org/support/topic/allow-specific-url/

**Comment by jwds1178** [comment]
For reference, the specific Wordfence two-factor URI that I'd exempted within the _dashboard_redirect_ functions is _/wp-admin/admin.php?page=WFLS_

**Comment by zackkatz** [comment]
Excellent, thanks @jwds1178 👍

**Comment by zackkatz** [comment]
@jwds1178 This is included in Version 1.2. Thanks for pointing this out!
