### ISSUE TITLE
Conflict between Remove Dashboard Access plugin and WP 2FA plugin

### ISSUE THREAD

**Issue by valueshopper** [trustedlogin/Remove-Dashboard-Access#36]
No problem for users who have already configured their 2FA but for new users, after entering their login details, when they would be sent to the 2FA setup, they get the "too many redirects" error.  Fixed by deactivating Remove Dashboard Access plugin.  Any fix that keeps this plugin usable?

**Comment by zackkatz** [comment]
Thanks for reporting—we will look into this.

**Comment by zackkatz** [comment]
This appears to no longer be a problem with the WP 2FA plugin; they must have changed their onboarding to be in-screen modals.
