### ISSUE TITLE
Ability to whitelist exception URLs

### ISSUE THREAD

**Issue by whittede** [trustedlogin/Remove-Dashboard-Access#38]
Hi there,

I was just checking in to see if we are any closer to having exception URLs be implemented into this plugin.

The plugin aggressively redirects ALL traffic from the backend, including instances from automated services such as those trying to make AJAX requests.

It looks like people have asked for a feature for a "whitelist" of URLs that you can add <a href="https://wordpress.org/support/topic/post-request-to-admin-post-php/" rel="noopener" target="_blank">here</a>, <a href="https://wordpress.org/support/topic/conflict-with-mailpoet-plugin-2/" rel="noopener" target="_blank">here</a>, <a href="https://wordpress.org/support/topic/allow-specific-url/" rel="noopener" target="_blank">here</a>, and <a href="https://wordpress.org/support/topic/exception-urls/" rel="noopener" target="_blank">here</a>.

It looks like <a href="https://wordpress.org/support/topic/exception-urls/#post-14915749" rel="noopener" target="_blank">here</a> it was mentioned that this could become a feature. Is there a status update on implementing this? It severely limits use cases where this plugin can be implemented without it.

Thanks

**Comment by whittede** [comment]
Any updates on this?

**Comment by zackkatz** [comment]
This is now possible using [the `rda_allowlist` filter](https://wordpress.org/plugins/remove-dashboard-access-for-non-admins/#how%20can%20i%20allow%20access%20to%20specific%20pages%20of%20the%20dashboard%3F).

There may be a need for an additional filter that checks against a full URL, but I wanted to start small and see if that addressed the requirements.
